# Generated by Django 5.2.4 on 2025-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.URLField(blank=True, null=True, verbose_name='Resume'),
        ),
    ]
