# Generated by Django 5.2.4 on 2025-07-12 09:22

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('address', models.CharField(max_length=50, verbose_name='')),
                ('job_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], default='Permanent', max_length=50, verbose_name='')),
                ('education', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd')], default='Bachelors', max_length=50, verbose_name='')),
                ('industry', models.CharField(choices=[('Permanent', 'Business'), ('Temporary', 'It'), ('Internship', 'Banking'), ('Education', 'Education'), ('Telecommunication', 'Telecommunication'), ('Others', 'Others')], default='Permanent', max_length=50, verbose_name='')),
                ('experience', models.CharField(choices=[('No experience', 'No Experience'), ('1 Year', 'One Year'), ('2 Year', 'To Year'), ('3 Year above', 'Three Year Plus')], default='No experience', max_length=50, verbose_name='')),
                ('salary', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='')),
                ('positions', models.PositiveIntegerField(default=1, verbose_name='')),
                ('company', models.CharField(max_length=50, null=True, verbose_name='')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('last_date', models.DateTimeField(default=job.models.return_date_time, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
