# Generated by Django 5.2.4 on 2025-07-14 07:07

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_address_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=50, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateTimeField(default=job.models.return_date_time, verbose_name='Last Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='positions',
            field=models.PositiveIntegerField(default=1, verbose_name='Positions'),
        ),
    ]
