# Generated by Django 5.2.4 on 2025-07-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_candidatesapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesapplied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_applied', to='job.job', verbose_name='Job'),
        ),
    ]
