# Generated by Django 5.2.4 on 2026-03-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('No Experience', 'No Experience'), ('1 Year', 'One Year'), ('2 Year', 'To Year'), ('3 Year above', 'Three Year Plus')], default='No Experience', max_length=50, verbose_name='Experience'),
        ),
    ]
